//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;

namespace MmmMethody
{
	public class InsAndOuts
	{
		public InsAndOuts ()
		{
			StreamWriter writer ; 
			writer = new StreamWriter("test.txt");

			writer.WriteLine("hello world");

			writer.Close ();

			TextReader reader = new StreamReader("Test.txt"); 
			string line = reader.ReadLine(); 
			Console.WriteLine (line); 
			reader.Close();
		}
	}
}

